# Show debug messages
Debug: true

# Delay between when events occur
OccurenceDelay: 60

# Max tries the event manager has to trigger a random event
MaxTries: 10

# Worlds that events can occur in
Worlds: [world]

Events:
  AnvilFall:
    Enabled: true
    Probability: 1
    FallHeight: 15
    RemoveAfterFall: true
  CreeperExplode:
    Enabled: true
    Probability: 1
  Dinnerbone:
    Enabled: true
    Probability: 1
  ExpBottle:
    Enabled: true
    Probability: 1
    Amount: 20
  Fireworks:
    Enabled: true
    Probability: 1
    Amount: 10
    MaxRadius: 150
  FoodCook:
    Enabled: true
    Probability: 1
  FrightenSheep:
    Enabled: true
    Probability: 1
  GeomagneticReversal:
    Enabled: true
    Probability: 1
    Duration: 15
  MobHorde:
    Enabled: true
    Probability: 1
    Amount: 15
    MaxRadius: 150
  OreSmelt:
    Enabled: true
    Probability: 1
  PvP:
    Enabled: true
    Probability: 1
    Rewards:
      - Material: DIAMOND
        Amount: 1
      - Material: GOLD_INGOT
        Amount: 5
  SolarFlare:
    Enabled: true
    Probability: 1
    Duration: 5
  Sound:
    Enabled: true
    Probability: 1
    Amount: 3